### ISSUE TITLE
MG 2.10 d3 incompatibility

### ISSUE THREAD

**Issue by ghost** [dgilperez/metrics-graphics-rails#3]
MG 2.10 has `interpolate: d3.curveCatmullRom.alpha(0)`, but it seems that `curveCatmullRom` was introduced in a later d3 version than the 3.5 specified in the MGR gemspec.  At least I assume that the case after getting js errors about `d3.curveCatmullRom` being undefined with MGR 2.10.1 and 2.10.1.1, but these not occurring with 2.9.0.2.

I guess this just needs a gemspec update?

**Comment by dgilperez** [comment]
Thanks @jjgreen! Sounds ok to me. I'm not having much time lately, but if you care to send a PR I'll review it.

**Comment by X1ting** [comment]
fixed just by gem updating.

**Comment by ghost** [comment]
Confirmed that this fixes the issue in my application, many thanks!
